### ISSUE TITLE
Is there any way to filter both L1 / L2 events, or call both L1 / L2 contracts in the same project?

### ISSUE THREAD

**Issue by formingform** [alisinabh/elixir_ethers#71]
In my test project, I want to filter both L1 / L2 events, or call both L1 / L2 contracts, is there any way to do this?
Thanks

**Comment by alisinabh** [comment]
Although Ethers does not have a concept of L1 or L2s (As other web3 clients), You can achieve this by using different RPC URLs for the different networks you want to interact with.

In order to do that you need to specify the RPC URL for each request in `rpc_opts` like the following.

```elixir
Ethers.Contracts.ERC20.name()
|> Ethers.call(rpc_opts: [url: "[NETWORK RPC URL]"])
```

You can use https://chainlist.org/ to get a public node RPC URL for the network you want to interact with.

I will close this for hygiene but please feel free to re-open if this doesn't fix your issue.
